const ContentProps = [
    {
        id: 1,
        color: "blue",
        avatarText: "A",
        title: "Shrimp and Chorizo Paella",
        date: "September 14, 2016",
        imageSrc: "images/web.jpg",
        description: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
        id: 2,
        color: "green",
        avatarText: "B",
        title: "Shrimp and Chorizo Paella",
        date: "September 14, 2016",
        imageSrc: "images/graphic.jpg",
        description: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
        id: 3,
        color: "grey",
        avatarText: "C",
        title: "Shrimp and Chorizo Paella",
        date: "September 14, 2016",
        imageSrc: "images/wordpress.jpg",
        description: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
        id: 4,
        color: "pink",
        avatarText: "D",
        title: "Shrimp and Chorizo Paella",
        date: "September 14, 2016",
        imageSrc: "images/seo.jpg",
        description: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
        id: 5,
        color: "red",
        avatarText: "E",
        title: "Shrimp and Chorizo Paella",
        date: "September 14, 2016",
        imageSrc: "images/ai.jpg",
        description: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
        id: 6,
        color: "yellow",
        avatarText: "F",
        title: "Shrimp and Chorizo Paella",
        date: "September 14, 2016",
        imageSrc: "images/marketing.jpg",
        description: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
];

export default ContentProps;